# Generated by Django 4.2.6 on 2023-10-15 21:25

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=7, unique=True)),
                ('is_student', models.BooleanField(default=False)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=4, null=True)),
                ('contact', models.CharField(max_length=11, null=True, unique=True)),
                ('street_address', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=15, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('years_of_experience', models.CharField(choices=[('None', 'None'), ('1 Year', '1 Year'), ('3 years', '3 Years'), ('5 Years', '5 Years'), ('7 Years and above', '7 Years and above')], max_length=17, null=True)),
                ('linkedin_profile', models.URLField(null=True)),
                ('area_of_interest', models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('Web 3', 'Web 3'), ('Network Security', 'Network Security'), ('Digital Marketing', 'Digital Marketing'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Software Development', 'Software Development'), ('Embedded Software Engineering', 'Embedded Software Engineering'), ('Mobile Application Development', 'Mobile Application Development'), ('Graphics Design', 'Graphics Design'), ('Database Systems', 'Database Systems'), ('Computer Networking', 'Computer Networking'), ('Digital/Affiliate Marketing', 'Digital/Affiliate Marketing'), ('Other', 'Other')], max_length=35, null=True)),
                ('about_me', models.TextField(null=True)),
                ('is_instructor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
