# Generated by Django 4.2.6 on 2023-10-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='years_of_experience',
            field=models.CharField(choices=[('None', 'None'), ('1 Year', '1 Year'), ('3 Years', '3 Years'), ('5 Years', '5 Years'), ('7 Years and above', '7 Years and above')], max_length=17, null=True),
        ),
    ]
