# Generated by Django 4.2.6 on 2023-10-31 13:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_mainuser_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='passport',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='resume',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
    ]
