# Generated by Django 4.2.6 on 2023-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mainuser_passport_mainuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='course_type',
            field=models.CharField(choices=[('Skilled', 'Skilled'), ('UnSkilled', 'UnSkilled')], max_length=9, null=True),
        ),
    ]
