# Generated by Django 4.2.6 on 2023-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mainuser_city_mainuser_contact_mainuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='area_of_interest',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('Web 3', 'Web 3'), ('Network Security', 'Network Security'), ('Digital Marketing', 'Digital Marketing'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Software Development', 'Software Development'), ('Embedded Software Engineering', 'Embedded Software Engineering'), ('Mobile Application Development', 'Mobile Application Development'), ('Graphics Design', 'Graphics Design'), ('Database Systems', 'Database Systems'), ('Computer Networking', 'Computer Networking'), ('Digital/Affiliate Marketing', 'Digital/Affiliate Marketing'), ('Other', 'Other')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='years_of_experience',
            field=models.CharField(choices=[('None', 'None'), ('1 Year', '1 Year'), ('3 years', '3 Years'), ('5 Years', '5 Years'), ('7 Years and above', '7 Years and above')], max_length=17, null=True),
        ),
    ]
