# Generated by Django 4.2.6 on 2023-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mainuser_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='course_type',
        ),
    ]
