# Generated by Django 4.2.6 on 2023-12-26 14:04

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_mainuser_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='status',
            field=models.CharField(choices=[('Skilled', 'Skilled'), ('UnSkilled', 'UnSkilled')], max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('image', models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
