# Generated by Django 4.2.6 on 2024-01-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_mainuser_affiliate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='refered_by',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='AffiliateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
