# Generated by Django 4.2.6 on 2024-01-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_mainuser_refered_by_affiliateaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='refered_by',
            new_name='referred_by',
        ),
    ]
