# Generated by Django 4.2.6 on 2024-01-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_recipientaccount_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipientAccount',
        ),
    ]
