# Generated by Django 4.2.6 on 2024-01-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_recipientholdingaccount_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipientholdingaccount',
            table='payment_model_recipientholdingaccount',
        ),
    ]
