# Generated by Django 4.2.6 on 2024-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_recipientholdingaccount_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
