# Generated by Django 4.2.6 on 2024-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_mainuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
