# Generated by Django 4.2.6 on 2023-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='public_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='q_and_a',
            field=models.BooleanField(default=False),
        ),
    ]
