# Generated by Django 4.2.6 on 2023-10-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_price_course_public_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_price',
            new_name='charge_status',
        ),
    ]
