# Generated by Django 4.2.6 on 2023-10-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_price_course_charge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='expectancy',
        ),
    ]
