# Generated by Django 4.2.6 on 2023-10-22 18:35

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_charge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
