# Generated by Django 4.2.6 on 2023-10-22 18:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_thumbnail_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('topic', models.ManyToManyField(to='courses.topic')),
            ],
        ),
    ]
