# Generated by Django 4.2.6 on 2023-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_topic_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
