# Generated by Django 4.2.6 on 2023-11-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_learning_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Skilled', 'Skilled'), ('UnSkilled', 'UnSkilled')], max_length=9, null=True),
        ),
    ]
