# Generated by Django 4.2.6 on 2023-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
