# Generated by Django 4.2.6 on 2023-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_topic_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='seconds',
            field=models.IntegerField(null=True),
        ),
    ]
