# Generated by Django 4.2.6 on 2023-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_content_hour_content_minutes_content_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
