# Generated by Django 4.2.6 on 2023-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_to_gain',
            field=models.TextField(null=True),
        ),
    ]
