# Generated by Django 4.2.6 on 2023-12-27 22:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_coursereview_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_file',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
    ]
