# Generated by Django 4.2.6 on 2024-01-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_state_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
