# Generated by Django 4.2.6 on 2024-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_refered_by_mainuser_referred_by'),
        ('courses', '0031_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='main_app.shopproduct'),
        ),
    ]
