# Generated by Django 4.2.6 on 2024-01-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_order_items_order_buyer_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.order'),
        ),
    ]
