# Generated by Django 4.2.6 on 2024-01-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
