# Generated by Django 4.2.6 on 2024-01-24 07:47

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_content_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='course-videos', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
