# Generated by Django 4.2.6 on 2024-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_content_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
