# Generated by Django 4.2.6 on 2024-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_ebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
