# Generated by Django 4.2.6 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_content_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='content',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seconds',
        ),
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.CharField(null=True),
        ),
    ]
