# Generated by Django 4.2.6 on 2024-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_remove_content_hour_remove_content_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
