# Generated by Django 4.2.6 on 2024-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_alter_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
