# Generated by Django 4.2.6 on 2024-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_mycourse_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
