# Generated by Django 4.2.6 on 2024-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_course_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='published',
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
