# Generated by Django 4.0 on 2024-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_remove_mycourse_published_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ManyToManyField(to='courses.Topic'),
        ),
    ]
