# Generated by Django 4.0 on 2024-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_content_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
