# Generated by Django 4.2.6 on 2024-02-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.URLField(),
        ),
    ]
