# Generated by Django 4.2.6 on 2024-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_alter_course_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.URLField(null=True),
        ),
    ]
