# Generated by Django 4.2.6 on 2024-03-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_alter_content_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='duration',
        ),
    ]
